/*  crypto-driver.c - The simplest kernel module.

* Copyright (C) 2013-2022 Xilinx, Inc
* Copyright (c) 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.

*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License along
*   with this program. If not, see <http://www.gnu.org/licenses/>.

*/
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/io.h>
#include <linux/interrupt.h>
#include <linux/cdev.h>  //core char driver 
#include <linux/fs.h>
#include <linux/of_platform.h>
#include <linux/mm.h>
#include <asm/pgtable.h>

#include <linux/of_address.h>
#include <linux/of.h>
#include <linux/mod_devicetable.h>
#include <linux/of_platform.h>

/* Standard module information, edit as appropriate */
MODULE_LICENSE("GPL");
MODULE_AUTHOR
    ("Xilinx Inc.");
MODULE_DESCRIPTION
    ("crypto-driver - loadable module template generated by petalinux-create -t modules");

#define DRIVER_NAME "crypto-driver"

/* Simple example of how to receive command line parameters to your module.
   Delete if you don't need them */



struct crypto_driver_local {
	int irq;
	unsigned long mem_start;
	unsigned long mem_end;
	void __iomem *base_addr;
	
	/* add the char device  gestion block   */
	
	dev_t dev_num;           /* 自动分配的主次设备号 */
    struct cdev cdev;        /* 字符设备核心结构体 */
    struct class *class;     /* 用于自动创建 /dev 节点的类 */
    struct device *device;   /* 设备节点指针 */
};

static irqreturn_t crypto_driver_irq(int irq, void *lp)
{
	printk("crypto-driver interrupt\n");
	return IRQ_HANDLED;
}


/* 1. 当用户程序 open "/dev/crypto-driver" 时触发 */
static int crypto_driver_open(struct inode *inode, struct file *filp)
{
    struct crypto_driver_local *lp;
    /* 逆向思维：通过 inode 里的 cdev 指针，找到包裹它的整个 lp 结构体 */
    lp = container_of(inode->i_cdev, struct crypto_driver_local, cdev);
    /* 把 lp 存进文件的私有数据中，这样下方的 mmap 函数就能直接拿来用 */
    filp->private_data = lp; 
    return 0;
}

/* 2. 当用户程序 close 设备时触发 */
static int crypto_driver_release(struct inode *inode, struct file *filp)
{
    return 0;
}

/* 3. 核心：当用户程序调用 mmap 时，将物理地址映射给用户空间 */
static int crypto_driver_mmap(struct file *filp, struct vm_area_struct *vma)
{
    struct crypto_driver_local *lp = filp->private_data; /* 从 open 存的私有数据里取出 lp */
    unsigned long size = vma->vm_end - vma->vm_start;

    /* 寄存器映射铁律：关闭 CPU 的 Cache 优化，防止读到硬件的缓存旧数据 */
    vma->vm_page_prot = pgprot_noncached(vma->vm_page_prot);

    /* 核心函数：把物理地址（lp->mem_start）转为页帧号，映射到用户的虚拟区间（vma->vm_start） */
    if (remap_pfn_range(vma, vma->vm_start, lp->mem_start >> PAGE_SHIFT, size, vma->vm_page_prot)) {
        pr_err("crypto-driver: mmap remap_pfn_range failed\n");
        return -EAGAIN;
    }
    return 0;
}

/* 4. 将上面写好的三个函数打包绑定 */
static const struct file_operations crypto_fops = {
    .owner   = THIS_MODULE,
    .open    = crypto_driver_open,
    .release = crypto_driver_release,
    .mmap    = crypto_driver_mmap,
};

static int crypto_driver_probe(struct platform_device *pdev)
{
	struct resource *r_irq; /* Interrupt resources */
	struct resource *r_mem; /* IO mem resources */
	struct device *dev = &pdev->dev;
	struct crypto_driver_local *lp = NULL;

	int rc = 0;
	dev_info(dev, "Device Tree Probing\n");
	/* Get iospace for the device */
	r_mem = platform_get_resource(pdev, IORESOURCE_MEM, 0);
	if (!r_mem) {
		dev_err(dev, "invalid address\n");
		return -ENODEV;
	}
	lp = (struct crypto_driver_local *) kmalloc(sizeof(struct crypto_driver_local), GFP_KERNEL);
	if (!lp) {
		dev_err(dev, "Cound not allocate crypto-driver device\n");
		return -ENOMEM;
	}
	dev_set_drvdata(dev, lp);
	lp->mem_start = r_mem->start;
	lp->mem_end = r_mem->end;

	if (!request_mem_region(lp->mem_start,
				lp->mem_end - lp->mem_start + 1,
				DRIVER_NAME)) {
		dev_err(dev, "Couldn't lock memory region at %p\n",
			(void *)lp->mem_start);
		rc = -EBUSY;
		goto error1;
	}

	lp->base_addr = ioremap(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	
	if (!lp->base_addr) {
		dev_err(dev, "crypto-driver: Could not allocate iomem\n");
		rc = -EIO;
		goto error2;
	}
	
	/* -------- 新增：注册字符设备并自动创建 /dev/ 节点 -------- */

    /* A. 动态申请一个主设备号 */
    rc = alloc_chrdev_region(&lp->dev_num, 0, 1, DRIVER_NAME);
    if (rc < 0) {
        dev_err(dev, "Failed to allocate char device region\n");
        goto error3; /* 如果失败，跳到错误处理释放 ioremap */
    }

    /* B. 初始化字符设备并绑定我们刚才写的 crypto_fops */
    cdev_init(&lp->cdev, &crypto_fops);
    lp->cdev.owner = THIS_MODULE;
    rc = cdev_add(&lp->cdev, lp->dev_num, 1);
    if (rc < 0) {
        dev_err(dev, "Failed to add cdev\n");
        goto error4;
    }

    /* C. 在 sysfs 中创建一个类，名字叫 "crypto-class" */
    lp->class = class_create(THIS_MODULE,"crypto-class");
    if (IS_ERR(lp->class)) {
        rc = PTR_ERR(lp->class);
        goto error5;
    }

    /* D. 在 /dev/ 目录下真正创建出 "crypto-driver" 文件节点 */
    lp->device = device_create(lp->class, NULL, lp->dev_num, NULL, DRIVER_NAME);
    if (IS_ERR(lp->device)) {
        rc = PTR_ERR(lp->device);
        goto error6;
    }
	
	

	/* Get IRQ for the device */
    r_irq = platform_get_resource(pdev, IORESOURCE_IRQ, 0);
    if (!r_irq) {
        dev_info(dev, "no IRQ found\n");
        dev_info(dev, "crypto-driver at %pa mapped to %p\n",
                 &lp->mem_start,
                 lp->base_addr);
        lp->irq = 0; /* 显式地将中断号记为 0，防止 remove 函数释放野中断 */
    } else {
        lp->irq = r_irq->start;
        rc = request_irq(lp->irq, &crypto_driver_irq, 0, DRIVER_NAME, lp);
        
        /* 💡 这样对齐后，逻辑层次一目了然 */
        if (rc) {
            dev_err(dev, "testmodule: Could not allocate interrupt %d.\n",
                    lp->irq);
            goto error7;
        }
    }

    dev_info(dev, "crypto-driver at 0x%08x mapped to 0x%08x, irq=%d\n",
             (unsigned int __force)lp->mem_start,
             (unsigned int __force)lp->base_addr,
             lp->irq);
    return 0;
error7:
    /* 如果 request_irq 失败了：销毁 /dev/ 下的物理文件节点 */
    device_destroy(lp->class, lp->dev_num);

error6:
    /* 如果 device_create 失败了：销毁 sysfs 中的类 */
    class_destroy(lp->class);

error5:
    /* 如果 class_create 失败了：从系统内核中移除字符设备块 */
    cdev_del(&lp->cdev);

error4:
    /* 如果 cdev_add 失败了：注销申请到的主次设备号 */
    unregister_chrdev_region(lp->dev_num, 1);

error3:
    /* 如果 alloc_chrdev_region 失败了：解开内核虚拟空间映射 (原本的) */
    iounmap(lp->base_addr);

error2:
    /* 如果 ioremap 失败了：释放独占的物理内存区域 (原本的) */
    release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);

error1:
    /* 如果 request_mem_region 失败了：释放 lp 结构体本身的堆内存 (原本的) */
    kfree(lp);
    dev_set_drvdata(dev, NULL);
	return rc;
}

static int crypto_driver_remove(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
    	struct crypto_driver_local *lp = dev_get_drvdata(dev);

    /* 1. 如果申请了中断，先释放中断 */
    if (lp->irq > 0) {
        free_irq(lp->irq, lp);
    }
    
    /* 2. 【新增加】倒序注销字符设备三件套 */
    device_destroy(lp->class, lp->dev_num);
    class_destroy(lp->class);
    cdev_del(&lp->cdev);
    unregister_chrdev_region(lp->dev_num, 1);
    
    /* 3. 释放原本模版里的内存和映射 */
    iounmap(lp->base_addr);
    release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
    kfree(lp);
    dev_set_drvdata(dev, NULL);
	return 0;
}

#ifdef CONFIG_OF
static struct of_device_id crypto_driver_of_match[] = {
	{ .compatible = "xlnx,crypto-first-ip-1.0", },
	{ /* end of list */ },
};
MODULE_DEVICE_TABLE(of, crypto_driver_of_match);
#else
# define crypto_driver_of_match NULL
#endif


static struct platform_driver crypto_driver_driver = {
	.driver = {
		.name = DRIVER_NAME,
		.owner = THIS_MODULE,
		.of_match_table	= crypto_driver_of_match,
	},
	.probe		= crypto_driver_probe,
	.remove		= crypto_driver_remove,
};



static int __init crypto_driver_init(void)
{
	printk("<1>It is initializated.\n");
	
	return platform_driver_register(&crypto_driver_driver);
}


static void __exit crypto_driver_exit(void)
{
	platform_driver_unregister(&crypto_driver_driver);
	printk(KERN_ALERT "exit crypto module.\n");
}

module_init(crypto_driver_init);
module_exit(crypto_driver_exit);
